Вывод тиков в tmux pane:
test/reset test/rollback test/shut_down

diff --git a/test/setup b/test/setup
--- a/test/setup
+++ b/test/setup
@@ -1,19 +1,24 @@
 #!/bin/bash
-
 # тестирование "наработкой на отказ"  конфигурационных скриптов
 # install не тестирую, чтобы не создавать большой трафик
 
 # safe bash
-set -o errexit -o noclobber -o nounset -o pipefail
+set -o errexit -o noclobber -o nounset -o pipefail -o xtrace
 
 # get config
 readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
 . "${root_dir}/load_config.bash"
 
-. "${lib_dir}/tick.bash"
+. "${lib_dir}/tmux.bash"
+. "${lib_dir}/power_off.bash"
 
-while true
-do
-	tick+
-	"${setup_dir}/setup"
-done
+tmux_init
+
+tmux respawn-pane -k "${test_dir}/setup1"
+
+tmux_attach
+
+# Finish, cleanup
+power_off
+
+exit 0
diff --git a/test/shut_down b/test/shut_down
--- a/test/shut_down
+++ b/test/shut_down
@@ -1,18 +1,22 @@
 #!/bin/bash
 # Тест на стабильность VirtualBox на включение/выключение
 # safe bash
-set -o errexit -o noclobber -o nounset -o pipefail
+set -o errexit -o noclobber -o nounset -o pipefail -o xtrace
 
+# get config
 readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
 . "${root_dir}/load_config.bash"
 
-. "${lib_dir}/power_on.bash"
-. "${lib_dir}/shut_down.bash"
-. "${lib_dir}/tick.bash"
+. "${lib_dir}/tmux.bash"
+. "${lib_dir}/power_off.bash"
 
-while true
-do
-	tick+
-	power_on
-	shut_down
-done
+tmux_init
+
+tmux respawn-pane -k "${test_dir}/shut_down1"
+
+tmux_attach
+
+# Finish, cleanup
+power_off
+
+exit 0
