lib/cleanup.bash
Функция очистки после завершения работы скрипта, нормально, по
требованию пользователя (Ctrl-C или Ctrl-d из tmux) или по ошибке в
скрипте.
Выключает виртуалки и останавливает tmux сервер.

diff --git a/setup/create b/setup/create
--- a/setup/create
+++ b/setup/create
@@ -8,6 +8,7 @@ readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
 
 . "${lib_dir}/vm_ssh.bash"
 . "${lib_dir}/tmux.bash"
+. "${lib_dir}/cleanup.bash"
 
 # create_vms
 if $autoVirtualBox
@@ -109,6 +110,7 @@ then
 	export dvd_iso ssh_public_key vboxnet_if
 fi
 
+trap cleanup EXIT
 tmux_init
 declare -i n=${#vm_name[@]} i=0
 for h in "${!vm_name[@]}"
@@ -123,6 +125,6 @@ do
 done; unset h n i
 tmux select-layout tiled
 tmux_attach
-
-# Наличине скриншота create будет маркером, что распараллелеиная установка пакетов отработала нормально
+# Наличине скриншота create будет маркером, что распараллелеиная установка пакетов отработала нормально.
 exec "${setup_dir}/install"
+# cleanup by trap on error
diff --git a/setup/install b/setup/install
--- a/setup/install
+++ b/setup/install
@@ -8,12 +8,14 @@ readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
 
 . "${lib_dir}/vm_ssh.bash"
 . "${lib_dir}/tmux.bash"
+. "${lib_dir}/cleanup.bash"
 if $autoVirtualBox
 then
 	. "${lib_dir}/delete_snapshot.bash"
 	. "${lib_dir}/rollback.bash"
 fi
 
+trap cleanup EXIT
 if $autoVirtualBox
 then
 	rollback 'create'
@@ -38,6 +40,6 @@ do
 done; unset h n i
 tmux select-layout tiled
 tmux_attach
-
-# Наличине скриншота install будет маркером, что распараллелеиная установка пакетов отработала нормально
+# Наличине скриншота install будет маркером, что распараллелеиная установка пакетов отработала нормально.
 exec "${setup_dir}/setup"
+# cleanup by trap on error
diff --git a/setup/setup b/setup/setup
--- a/setup/setup
+++ b/setup/setup
@@ -8,12 +8,14 @@ readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
 
 . "${lib_dir}/vm_ssh.bash"
 . "${lib_dir}/tmux.bash"
+. "${lib_dir}/cleanup.bash"
 if $autoVirtualBox
 then
 	. "${lib_dir}/delete_snapshot.bash"
 	. "${lib_dir}/rollback.bash"
 fi
 
+trap cleanup EXIT
 if $autoVirtualBox
 then
 	rollback 'install'
@@ -38,6 +40,6 @@ do
 	let i+=1
 done; unset c n i
 tmux_attach
-
-# Наличине скриншота setup будет маркером, что распараллелеиная настройка кластеров отработала нормально
+# Наличине скриншота setup будет маркером, что распараллелеиная настройка кластеров отработала нормально.
 exit 0
+# cleanup by trap
